[tool.poetry]
name = "simple_app"
version = "0.1.0"
description = "simple_app"
authors = ["Alex"]

[tool.poetry.dependencies]
python = "^3.11"
requests = ">=2.26.1"
django = "3.2.24"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"